# Generated by Django 2.2.16 on 2020-09-12 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('name', models.CharField(default='about', editable=False, max_length=5, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='about_image')),
                ('content', models.TextField(max_length=10000)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('link', models.URLField(max_length=100)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('types', models.CharField(choices=[('fa-linkedin', 'Linkedin'), ('fa-instagram', 'Instagram'), ('fa-github', 'Github'), ('fa-twitter', 'Twitter'), ('fa-mail', 'Email')], max_length=20, primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=100)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('no_of_visits', models.IntegerField(default=1)),
                ('last_visited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=20)),
                ('name_content', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Visit_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.People')),
            ],
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation_name', models.CharField(max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Background_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mainPage/background_img')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.Portfolio')),
            ],
        ),
    ]
