# Generated by Django 2.2.16 on 2020-09-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit_detail',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='visit_detail',
            name='country',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='visit_detail',
            name='region',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
