# Generated by Django 2.2.16 on 2020-09-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20200913_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_detail',
            name='user_agent',
            field=models.CharField(max_length=150),
        ),
    ]
